exports.SHOPIFY_API_SECRET = process.env.SHOPIFY_API_SECRET;
exports.SHOPIFY_API_KEY = process.env.SHOPIFY_API_KEY;
exports.HOWHEARD_PUBLIC_URL_ROOT = process.env.HOWHEARD_PUBLIC_URL_ROOT;
exports.HOWHEARD_TRIAL_DAYS = 30;
exports.HOWHEARD_APP_CLIENT_ID = 1439668;
exports.HOWHEARD_APP_TEST = null;
